CREATE DATABASE IF NOT EXISTS ristogo;
USE ristogo;

DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE restaurants (
	id INT NOT NULL AUTO_INCREMENT,
	userId INT,
	name VARCHAR(32) NOT NULL,
	genre VARCHAR(32),
	price ENUM('ECONOMIC', 'LOW', 'MIDDLE', 'HIGH', 'LUXURY'),
	city VARCHAR(32) NOT NULL,
	address VARCHAR(32) NOT NULL,
	description TEXT,
	seats INT UNSIGNED NOT NULL,
	openingHours ENUM('LUNCH', 'DINNER', 'BOTH') NOT NULL DEFAULT 'BOTH',
	PRIMARY KEY (id),
	UNIQUE (id, userId),
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reservations (
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	restaurantId INT NOT NULL,
	date DATE NOT NULL,
	time ENUM('LUNCH', 'DINNER') NOT NULL,
	seats INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (userId, date, time),
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (restaurantId)
		REFERENCES restaurants(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
