CREATE DATABASE IF NOT EXISTS ristogo;
USE ristogo;

DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE,
	password CHAR(64) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE restaurants (
	id INT NOT NULL AUTO_INCREMENT,
	ownerId INT NOT NULL,
	name VARCHAR(45) NOT NULL,
	genre ENUM('PIZZA', 'JAPANESE', 'MEXICAN', 'ITALIAN', 'STEAKHOUSE'),
	price ENUM('ECONOMIC', 'LOW', 'MIDDLE', 'HIGH', 'LUXURY'),
	city VARCHAR(32),
	address VARCHAR(32),
	description TEXT,
	seats INT UNSIGNED NOT NULL DEFAULT 0,
	openingHours ENUM('LUNCH', 'DINNER', 'BOTH') NOT NULL DEFAULT 'BOTH',
	PRIMARY KEY (id),
	FOREIGN KEY (ownerId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reservations (
	id INT NOT NULL AUTO_INCREMENT,
	userId INT NOT NULL,
	restaurantId INT NOT NULL,
	date DATE NOT NULL,
	time ENUM('LUNCH', 'DINNER') NOT NULL,
	seats INT UNSIGNED NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (userId, date, time),
	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (restaurantId)
		REFERENCES restaurants(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
